<?php

// The curated icon set of the React icon-picker (about 220 lucide icons): [kebab-case name, category, English keywords, Arabic keywords].
return [
    ['house', 'general', 'home house start', 'رئيسية بيت منزل'],
    ['star', 'general', 'favorite rating', 'نجمة مفضلة تقييم'],
    ['heart', 'general', 'like love favorite', 'قلب اعجاب حب'],
    ['bookmark', 'general', 'save saved', 'حفظ علامة'],
    ['flag', 'general', 'report milestone', 'علم راية'],
    ['tag', 'general', 'label price', 'وسم بطاقة'],
    ['tags', 'general', 'labels', 'وسوم'],
    ['pin', 'general', 'pinned', 'تثبيت دبوس'],
    ['map-pin', 'general', 'location place', 'موقع مكان'],
    ['calendar', 'general', 'date schedule', 'تقويم تاريخ'],
    ['calendar-days', 'general', 'days month', 'ايام شهر'],
    ['clock', 'general', 'time hour', 'ساعة وقت'],
    ['alarm-clock', 'general', 'alarm reminder', 'منبه تذكير'],
    ['timer', 'general', 'stopwatch', 'مؤقت'],
    ['hourglass', 'general', 'wait pending', 'انتظار'],
    ['bell', 'general', 'notification alert', 'اشعار تنبيه'],
    ['search', 'general', 'find magnifier', 'بحث'],
    ['settings', 'general', 'gear preferences', 'اعدادات'],
    ['sliders-horizontal', 'general', 'controls filter', 'تحكم'],
    ['filter', 'general', 'funnel', 'تصفية'],
    ['menu', 'general', 'hamburger navigation', 'قائمة'],
    ['ellipsis', 'general', 'more dots', 'المزيد'],
    ['plus', 'general', 'add new', 'اضافة جديد'],
    ['minus', 'general', 'remove less', 'ناقص'],
    ['check', 'general', 'done tick', 'تم صح'],
    ['circle-check', 'general', 'success complete', 'نجاح اكتمال'],
    ['circle-x', 'general', 'error cancel', 'خطأ الغاء'],
    ['x', 'general', 'close', 'اغلاق'],
    ['info', 'general', 'information', 'معلومات'],
    ['circle-question-mark', 'general', 'help question', 'مساعدة سؤال'],
    ['eye', 'general', 'view visible', 'عرض اظهار'],
    ['eye-off', 'general', 'hidden hide', 'اخفاء'],
    ['copy', 'general', 'duplicate', 'نسخ'],
    ['trash-2', 'general', 'delete bin', 'حذف سلة'],
    ['pencil', 'general', 'edit write', 'تعديل قلم'],
    ['download', 'general', 'save', 'تنزيل'],
    ['upload', 'general', 'send file', 'رفع'],
    ['share-2', 'general', 'share', 'مشاركة'],
    ['link', 'general', 'url chain', 'رابط'],
    ['paperclip', 'general', 'attachment', 'مرفق'],
    ['lock', 'general', 'secure private', 'قفل خاص'],
    ['lock-open', 'general', 'unlock', 'فتح'],
    ['key', 'general', 'password access', 'مفتاح كلمة مرور'],
    ['shield', 'general', 'protection', 'درع حماية'],
    ['shield-check', 'general', 'verified secure', 'حماية موثقة'],
    ['power', 'general', 'on off', 'تشغيل'],
    ['zap', 'general', 'lightning fast energy', 'برق سريع طاقة'],
    ['sparkles', 'general', 'magic ai new', 'لمعان سحر ذكاء'],
    ['lightbulb', 'general', 'idea tip', 'فكرة'],
    ['target', 'general', 'goal aim', 'هدف'],
    ['puzzle', 'general', 'plugin extension', 'اضافة'],
    ['layout-grid', 'general', 'grid apps', 'شبكة تطبيقات'],
    ['layout-dashboard', 'general', 'dashboard overview', 'لوحة'],
    ['list', 'general', 'items rows', 'قائمة'],
    ['list-todo', 'general', 'tasks todo', 'مهام'],
    ['list-checks', 'general', 'checklist', 'قائمة تحقق'],
    ['layers', 'general', 'stack levels', 'طبقات'],
    ['fingerprint', 'general', 'identity biometric', 'بصمة'],
    ['qr-code', 'general', 'scan code', 'رمز'],
    ['barcode', 'general', 'scan product', 'باركود'],
    ['file', 'files', 'document', 'ملف'],
    ['file-text', 'files', 'document text', 'مستند نص'],
    ['files', 'files', 'documents copies', 'ملفات'],
    ['file-spreadsheet', 'files', 'excel csv table', 'جدول بيانات'],
    ['file-image', 'files', 'picture', 'ملف صورة'],
    ['file-code', 'files', 'source code', 'ملف برمجي'],
    ['file-json', 'files', 'json data', 'ملف جيسون'],
    ['file-archive', 'files', 'zip compressed', 'ملف مضغوط'],
    ['folder', 'files', 'directory', 'مجلد'],
    ['folder-open', 'files', 'directory open', 'مجلد مفتوح'],
    ['folder-kanban', 'files', 'project board', 'مشروع لوحة'],
    ['archive', 'files', 'archived box storage', 'ارشيف'],
    ['inbox', 'files', 'incoming', 'وارد'],
    ['newspaper', 'files', 'news article', 'اخبار مقال'],
    ['notebook', 'files', 'notes journal', 'دفتر ملاحظات'],
    ['sticky-note', 'files', 'note memo', 'ملاحظة'],
    ['clipboard-list', 'files', 'list form', 'حافظة قائمة'],
    ['clipboard-check', 'files', 'approved checklist', 'حافظة موافقة'],
    ['book', 'files', 'manual', 'كتاب'],
    ['book-open', 'files', 'reading docs', 'كتاب مفتوح'],
    ['library', 'files', 'collection', 'مكتبة'],
    ['printer', 'files', 'print', 'طابعة'],
    ['table', 'files', 'grid rows', 'جدول'],
    ['mail', 'communication', 'email message', 'بريد رسالة'],
    ['mail-open', 'communication', 'read email', 'بريد مفتوح'],
    ['send', 'communication', 'submit paper plane', 'ارسال'],
    ['message-square', 'communication', 'chat comment', 'محادثة تعليق'],
    ['message-circle', 'communication', 'chat bubble', 'رسالة'],
    ['phone', 'communication', 'call', 'هاتف اتصال'],
    ['video', 'communication', 'meeting camera film clip', 'فيديو اجتماع'],
    ['mic', 'communication', 'microphone voice', 'ميكروفون صوت'],
    ['megaphone', 'communication', 'announce campaign', 'اعلان حملة'],
    ['at-sign', 'communication', 'mention email', 'اشارة'],
    ['globe', 'communication', 'web world internet', 'عالم انترنت'],
    ['languages', 'communication', 'translate language', 'لغات ترجمة'],
    ['bot', 'communication', 'assistant robot ai', 'روبوت مساعد'],
    ['handshake', 'communication', 'deal partner', 'اتفاق شراكة'],
    ['building-2', 'business', 'company office organization', 'شركة مكتب مؤسسة'],
    ['briefcase', 'business', 'work job', 'حقيبة عمل'],
    ['landmark', 'business', 'bank government', 'بنك حكومة'],
    ['factory', 'business', 'industry manufacturing', 'مصنع صناعة'],
    ['warehouse', 'business', 'storage inventory', 'مستودع مخزن'],
    ['store', 'business', 'shop retail', 'متجر'],
    ['school', 'business', 'education', 'مدرسة'],
    ['graduation-cap', 'business', 'student academy', 'تخرج اكاديمية'],
    ['award', 'business', 'prize badge', 'جائزة'],
    ['medal', 'business', 'rank', 'ميدالية'],
    ['trophy', 'business', 'winner', 'كأس فوز'],
    ['crown', 'business', 'premium king', 'تاج مميز'],
    ['rocket', 'business', 'launch startup', 'صاروخ اطلاق'],
    ['flame', 'business', 'hot trending', 'لهب شائع'],
    ['diamond', 'business', 'gem value', 'الماس'],
    ['anchor', 'business', 'harbor stable', 'مرساة'],
    ['life-buoy', 'business', 'support help', 'دعم'],
    ['wallet', 'commerce', 'money', 'محفظة'],
    ['credit-card', 'commerce', 'payment card', 'بطاقة دفع'],
    ['banknote', 'commerce', 'cash money', 'نقد'],
    ['coins', 'commerce', 'money change', 'عملات'],
    ['receipt', 'commerce', 'invoice bill', 'ايصال فاتورة'],
    ['shopping-cart', 'commerce', 'basket buy', 'سلة تسوق'],
    ['shopping-bag', 'commerce', 'purchase', 'حقيبة تسوق'],
    ['package', 'commerce', 'parcel product', 'طرد منتج'],
    ['boxes', 'commerce', 'inventory', 'صناديق'],
    ['box', 'commerce', 'container', 'صندوق'],
    ['truck', 'commerce', 'delivery shipping', 'توصيل شحن'],
    ['gift', 'commerce', 'present reward', 'هدية'],
    ['percent', 'commerce', 'discount', 'خصم'],
    ['dollar-sign', 'commerce', 'currency price', 'دولار سعر'],
    ['chart-bar', 'data', 'bar graph analytics', 'مخطط اعمدة تحليلات'],
    ['chart-line', 'data', 'line graph trend', 'مخطط خطي'],
    ['chart-pie', 'data', 'pie share', 'مخطط دائري'],
    ['trending-up', 'data', 'growth increase', 'نمو ارتفاع'],
    ['trending-down', 'data', 'decline decrease', 'انخفاض'],
    ['activity', 'data', 'pulse heartbeat', 'نشاط'],
    ['database', 'data', 'storage sql', 'قاعدة بيانات'],
    ['server', 'data', 'hosting', 'خادم'],
    ['hard-drive', 'data', 'disk storage', 'قرص'],
    ['cpu', 'data', 'processor chip', 'معالج'],
    ['wifi', 'data', 'network wireless', 'شبكة'],
    ['blocks', 'data', 'modules building', 'وحدات'],
    ['shapes', 'data', 'objects', 'اشكال'],
    ['user', 'people', 'person profile account', 'مستخدم شخص حساب'],
    ['user-round', 'people', 'person avatar', 'شخص'],
    ['users', 'people', 'team group people', 'فريق مجموعة'],
    ['smile', 'people', 'happy face', 'ابتسامة سعيد'],
    ['thumbs-up', 'people', 'approve like', 'موافقة اعجاب'],
    ['hand', 'people', 'stop wave', 'يد'],
    ['baby', 'people', 'child', 'طفل'],
    ['code', 'dev', 'programming brackets', 'برمجة كود'],
    ['terminal', 'dev', 'console shell cli', 'طرفية'],
    ['braces', 'dev', 'json object', 'اقواس'],
    ['git-branch', 'dev', 'version control', 'فرع'],
    ['git-pull-request', 'dev', 'merge review', 'طلب دمج'],
    ['bug', 'dev', 'issue defect', 'خلل خطأ برمجي'],
    ['plug', 'dev', 'integration connect api', 'توصيل تكامل'],
    ['laptop', 'dev', 'computer', 'حاسوب محمول'],
    ['monitor', 'dev', 'screen desktop', 'شاشة'],
    ['smartphone', 'dev', 'mobile phone', 'جوال'],
    ['keyboard', 'dev', 'typing', 'لوحة مفاتيح'],
    ['mouse', 'dev', 'pointer', 'فأرة'],
    ['battery', 'dev', 'power charge', 'بطارية'],
    ['wrench', 'dev', 'tool fix settings', 'مفتاح صيانة'],
    ['hammer', 'dev', 'build tool', 'مطرقة بناء'],
    ['atom', 'dev', 'science react', 'ذرة'],
    ['brain', 'dev', 'intelligence ai', 'دماغ ذكاء'],
    ['image', 'media', 'picture photo', 'صورة'],
    ['camera', 'media', 'photo', 'كاميرا'],
    ['film', 'media', 'movie cinema', 'فيلم سينما'],
    ['music', 'media', 'audio song', 'موسيقى'],
    ['headphones', 'media', 'listen audio', 'سماعات'],
    ['play', 'media', 'start media', 'تشغيل'],
    ['pause', 'media', 'stop media', 'ايقاف مؤقت'],
    ['tv', 'media', 'television screen', 'تلفاز'],
    ['gamepad-2', 'media', 'games controller', 'العاب'],
    ['palette', 'design', 'colors paint', 'الوان'],
    ['brush', 'design', 'paint art', 'فرشاة'],
    ['pen-tool', 'design', 'vector draw', 'قلم رسم'],
    ['scissors', 'design', 'cut', 'مقص'],
    ['ruler', 'design', 'measure', 'مسطرة'],
    ['hexagon', 'design', 'shape', 'سداسي'],
    ['sun', 'nature', 'day light weather', 'شمس طقس'],
    ['moon', 'nature', 'night dark', 'قمر ليل'],
    ['cloud', 'nature', 'weather storage', 'سحابة'],
    ['cloud-rain', 'nature', 'rain weather', 'مطر'],
    ['snowflake', 'nature', 'cold winter', 'ثلج شتاء'],
    ['umbrella', 'nature', 'rain cover', 'مظلة'],
    ['wind', 'nature', 'air breeze', 'رياح'],
    ['droplet', 'nature', 'water liquid', 'قطرة ماء'],
    ['leaf', 'nature', 'plant eco green', 'ورقة نبات'],
    ['tree-pine', 'nature', 'forest tree', 'شجرة'],
    ['flower-2', 'nature', 'bloom garden', 'زهرة'],
    ['mountain', 'nature', 'peak outdoor', 'جبل'],
    ['waves', 'nature', 'sea water', 'امواج بحر'],
    ['recycle', 'nature', 'sustainable eco', 'تدوير'],
    ['bird', 'nature', 'animal', 'طائر'],
    ['fish', 'nature', 'animal sea', 'سمكة'],
    ['car', 'travel', 'vehicle drive', 'سيارة'],
    ['bus', 'travel', 'transport', 'حافلة'],
    ['bike', 'travel', 'cycle', 'دراجة'],
    ['plane', 'travel', 'flight airport', 'طائرة سفر'],
    ['ship', 'travel', 'boat cruise', 'سفينة'],
    ['fuel', 'travel', 'gas station', 'وقود'],
    ['map', 'travel', 'directions', 'خريطة'],
    ['compass', 'travel', 'direction explore', 'بوصلة'],
    ['navigation', 'travel', 'gps route', 'ملاحة'],
    ['telescope', 'travel', 'explore discover', 'تلسكوب'],
    ['tent', 'travel', 'camping', 'خيمة'],
    ['heart-pulse', 'health', 'health heartbeat', 'صحة نبض'],
    ['stethoscope', 'health', 'doctor medical', 'سماعة طبيب'],
    ['pill', 'health', 'medicine', 'دواء'],
    ['flask-conical', 'health', 'lab science chemistry', 'مختبر كيمياء'],
    ['dumbbell', 'health', 'fitness gym', 'لياقة'],
    ['coffee', 'health', 'drink cafe', 'قهوة'],
    ['utensils', 'health', 'food restaurant', 'طعام مطعم'],
    ['pizza', 'health', 'food', 'بيتزا'],
    ['apple', 'health', 'fruit food', 'تفاحة'],
    ['beer', 'health', 'drink', 'مشروب'],
    ['wine', 'health', 'drink', 'عصير'],
    ['cake', 'health', 'birthday party', 'كعكة عيد ميلاد'],
];
