{{-- Internal: the words of the server-admin panels (port of web/src/components/server-admin/server-admin.tsx). Included with
     @include('nasaq::components.server-admin._strings'). Strings with a value use {n} / {name} placeholders, which the PHP and JS sides fill in.
     Plural helpers: totalOne / totalTwo / totalFew for the update count, forgetOne / retryOne for a single job, keyNoComment without a comment. --}}
@php
    if (! function_exists('nq_server_admin_strings')) {
        /** The built-in words for a locale, with $labels laid over them. */
        function nq_server_admin_strings(string $locale, array $labels = []): array
        {
            $ar = str_starts_with($locale, 'ar');
            $base = $ar ? [
                        'genericError' => 'حدث خطأ ما. حاول مرة أخرى.',
                        'cancel' => 'إلغاء',
                        'dismiss' => 'إغلاق',
                        'search' => 'بحث…',
                        'servicesTitle' => 'الخدمات',
                        'servicesDescription' => 'وحدات systemd على هذا الخادم. شغّلها أو أوقفها أو أعد تشغيلها أو اختر ما يعمل عند الإقلاع.',
                        'servicesTable' => 'وحدات الخدمات',
                        'service' => 'الخدمة',
                        'state' => 'الحالة',
                        'boot' => 'عند الإقلاع',
                        'memory' => 'الذاكرة',
                        'since' => 'منذ',
                        'states' => [
                            'active' => 'تعمل',
                            'inactive' => 'متوقفة',
                            'failed' => 'فشلت',
                            'activating' => 'قيد البدء',
                            'deactivating' => 'قيد الإيقاف',
                            'reloading' => 'قيد إعادة التحميل',
                        ],
                        'enabledAtBoot' => 'مفعّلة',
                        'disabledAtBoot' => 'معطّلة',
                        'actions' => [
                            'start' => 'تشغيل',
                            'stop' => 'إيقاف',
                            'restart' => 'إعادة التشغيل',
                            'reload' => 'إعادة تحميل الإعدادات',
                            'enable' => 'تفعيل عند الإقلاع',
                            'disable' => 'تعطيل عند الإقلاع',
                        ],
                        'viewLogs' => 'عرض السجلات',
                        'working' => 'جارٍ التنفيذ',
                        'confirmAction' => '{action}: {name}؟',
                        'confirmStop' => 'كل ما يعتمد على هذه الخدمة يتوقف عن العمل إلى أن تُشغَّل من جديد.',
                        'confirmRestart' => 'تتوقف الخدمة لحظة أثناء إعادة التشغيل.',
                        'confirmDisable' => 'لن تبدأ الخدمة وحدها بعد إعادة تشغيل الخادم.',
                        'servicesEmpty' => 'لا توجد خدمات',
                        'packagesTitle' => 'تحديثات الحزم',
                        'packagesDescription' => 'التحديثات المتاحة لهذا الخادم.',
                        'packagesTable' => 'التحديثات المتاحة',
                        'package' => 'الحزمة',
                        'version' => 'الإصدار',
                        'kind' => 'النوع',
                        'size' => 'الحجم',
                        'kinds' => [
                            'security' => 'أمني',
                            'kernel' => 'النواة',
                            'regular' => 'تحديث',
                        ],
                        'upToDate' => 'كل شيء محدَّث',
                        'upToDateBody' => 'لا توجد تحديثات بانتظارك.',
                        'lastChecked' => 'آخر فحص',
                        'neverChecked' => 'لم يُفحص بعد',
                        'checkNow' => 'فحص التحديثات',
                        'checking' => 'جارٍ الفحص',
                        'updateAll' => 'تحديث الكل',
                        'updateAllTitle' => 'تحديث {n} حزمة؟',
                        'updateAllBody' => 'قد تُعاد تشغيل الخدمات التي تستخدم مكتبة محدَّثة.',
                        'updateSelected' => 'تحديث المحدد',
                        'updateOne' => 'تحديث',
                        'updating' => 'جارٍ التحديث',
                        'securityCount' => '{n} أمنية',
                        'totalCount' => '{n} تحديثًا',
                        'download' => '{size} للتنزيل',
                        'rebootTitle' => 'يلزم إعادة التشغيل',
                        'rebootBody' => 'حُدِّثت النواة أو مكتبة أساسية. أعد تشغيل الخادم لتفعيلها.',
                        'reboot' => 'إعادة تشغيل الخادم',
                        'rebootConfirmTitle' => 'إعادة تشغيل الخادم؟',
                        'rebootConfirmBody' => 'كل ما عليه يتوقف دقيقة أو دقيقتين.',
                        'sshTitle' => 'مفاتيح SSH',
                        'sshDescription' => 'أي مفتاح يمكنه الدخول إلى أي خادم. علّم المربع لتثبيت المفتاح أو إزالته.',
                        'sshTable' => 'مفاتيح SSH حسب الخادم',
                        'sshKey' => 'المفتاح',
                        'sshCoverage' => '{n} من {total}',
                        'sshServers' => 'الخوادم',
                        'addKey' => 'إضافة مفتاح',
                        'addKeyTitle' => 'إضافة مفتاح SSH',
                        'addKeyBody' => 'الصق المفتاح العام، وهو الذي ينتهي بـ .pub. لا تلصق المفتاح الخاص أبدًا.',
                        'keyName' => 'الاسم',
                        'keyNamePlaceholder' => 'الحاسوب المحمول',
                        'keyNameRequired' => 'أعطِ المفتاح اسمًا.',
                        'publicKey' => 'المفتاح العام',
                        'keyProblems' => [
                            'empty' => 'الصق المفتاح العام.',
                            'format' => 'المفتاح العام سطر واحد: النوع ثم المفتاح ثم تعليق اختياري.',
                            'type' => 'نوع المفتاح غير معروف. استخدم ssh-ed25519 أو ssh-rsa أو ecdsa.',
                            'body' => 'نص المفتاح يبدو تالفًا. انسخه مرة أخرى.',
                            'private' => 'هذا مفتاح خاص. لا تلصقه أبدًا. الصق ملف .pub بدلًا منه.',
                        ],
                        'keyDetected' => 'مفتاح {type}، {comment}',
                        'addedOn' => 'أُضيف',
                        'lastUsed' => 'آخر استخدام',
                        'never' => 'أبدًا',
                        'installOnAll' => 'تثبيت على كل الخوادم',
                        'removeFromAll' => 'إزالة من كل الخوادم',
                        'deleteKey' => 'حذف المفتاح',
                        'deleteKeyTitle' => 'حذف {name}؟',
                        'deleteKeyBody' => 'يُزال المفتاح من كل خادم ثُبِّت عليه، ولا يستطيع من يستخدمه الدخول بعد الآن.',
                        'installedOn' => '{key} على {server}',
                        'noKeys' => 'لا توجد مفاتيح SSH بعد',
                        'noKeysBody' => 'أضف مفتاحًا عامًا ثم اختر الخوادم التي يمكنه الدخول إليها.',
                        'jobsTitle' => 'طابور المهام',
                        'jobsDescription' => 'العمل في الخلفية حسب الحالة. أعد محاولة ما فشل أو انسَه.',
                        'jobsTable' => 'المهام',
                        'job' => 'المهمة',
                        'queue' => 'الطابور',
                        'attempts' => 'المحاولات',
                        'when' => 'الوقت',
                        'status' => 'الحالة',
                        'jobStatuses' => [
                            'waiting' => 'بالانتظار',
                            'active' => 'تعمل',
                            'delayed' => 'مؤجلة',
                            'completed' => 'منتهية',
                            'failed' => 'فاشلة',
                        ],
                        'retry' => 'إعادة المحاولة',
                        'forget' => 'نسيان',
                        'retryFailed' => 'إعادة محاولة كل الفاشلة',
                        'forgetFailed' => 'نسيان كل الفاشلة',
                        'forgetTitle' => 'نسيان {n} مهام؟',
                        'forgetBody' => 'تُزال من الطابور ومن السجل. لا يمكن التراجع.',
                        'retryTitle' => 'إعادة محاولة {n} مهام؟',
                        'retryBody' => 'تعود إلى الطابور وتعمل من جديد.',
                        'details' => 'التفاصيل',
                        'errorLabel' => 'الخطأ',
                        'payloadLabel' => 'البيانات',
                        'noError' => 'لا يوجد خطأ مسجَّل.',
                        'close' => 'إغلاق',
                        'jobsEmpty' => 'لا توجد مهام',
                        'of' => '{a}/{b}',
                        'queueFilter' => 'الطابور',
                        'statusGroup' => 'حالة المهام',
                    ] : [
                        'genericError' => 'Something went wrong. Try again.',
                        'cancel' => 'Cancel',
                        'dismiss' => 'Dismiss',
                        'search' => 'Search…',
                        'servicesTitle' => 'Services',
                        'servicesDescription' => 'Systemd units on this server. Start, stop, restart or choose what runs at boot.',
                        'servicesTable' => 'Service units',
                        'service' => 'Service',
                        'state' => 'State',
                        'boot' => 'At boot',
                        'memory' => 'Memory',
                        'since' => 'Since',
                        'states' => [
                            'active' => 'Running',
                            'inactive' => 'Stopped',
                            'failed' => 'Failed',
                            'activating' => 'Starting',
                            'deactivating' => 'Stopping',
                            'reloading' => 'Reloading',
                        ],
                        'enabledAtBoot' => 'Enabled',
                        'disabledAtBoot' => 'Disabled',
                        'actions' => [
                            'start' => 'Start',
                            'stop' => 'Stop',
                            'restart' => 'Restart',
                            'reload' => 'Reload',
                            'enable' => 'Enable at boot',
                            'disable' => 'Disable at boot',
                        ],
                        'viewLogs' => 'View logs',
                        'working' => 'Working',
                        'confirmAction' => '{action} {name}?',
                        'confirmStop' => 'Anything that depends on this service stops working until it is started again.',
                        'confirmRestart' => 'The service is interrupted for a moment while it restarts.',
                        'confirmDisable' => 'The service will not start by itself after a reboot.',
                        'servicesEmpty' => 'No services',
                        'packagesTitle' => 'Package updates',
                        'packagesDescription' => 'Updates waiting on this server.',
                        'packagesTable' => 'Available updates',
                        'package' => 'Package',
                        'version' => 'Version',
                        'kind' => 'Type',
                        'size' => 'Size',
                        'kinds' => [
                            'security' => 'Security',
                            'kernel' => 'Kernel',
                            'regular' => 'Update',
                        ],
                        'upToDate' => 'Everything is up to date',
                        'upToDateBody' => 'There are no updates waiting.',
                        'lastChecked' => 'Last checked',
                        'neverChecked' => 'Not checked yet',
                        'checkNow' => 'Check for updates',
                        'checking' => 'Checking',
                        'updateAll' => 'Update all',
                        'updateAllTitle' => 'Update {n} packages?',
                        'updateAllBody' => 'Services that use an updated library may restart.',
                        'updateSelected' => 'Update selected',
                        'updateOne' => 'Update',
                        'updating' => 'Updating',
                        'securityCount' => '{n} security',
                        'totalCount' => '{n} updates',
                        'download' => '{size} to download',
                        'rebootTitle' => 'A restart is needed',
                        'rebootBody' => 'A kernel or core library was updated. Restart the server to use it.',
                        'reboot' => 'Restart server',
                        'rebootConfirmTitle' => 'Restart the server?',
                        'rebootConfirmBody' => 'Everything on it is offline for a minute or two.',
                        'sshTitle' => 'SSH keys',
                        'sshDescription' => 'Which keys can sign in to which server. Tick a box to install or remove a key.',
                        'sshTable' => 'SSH keys by server',
                        'sshKey' => 'Key',
                        'sshCoverage' => '{n} of {total}',
                        'sshServers' => 'Servers',
                        'addKey' => 'Add key',
                        'addKeyTitle' => 'Add an SSH key',
                        'addKeyBody' => 'Paste the public key, the one that ends in .pub. Never paste a private key.',
                        'keyName' => 'Name',
                        'keyNamePlaceholder' => 'Laptop',
                        'keyNameRequired' => 'Give the key a name.',
                        'publicKey' => 'Public key',
                        'keyProblems' => [
                            'empty' => 'Paste the public key.',
                            'format' => 'A public key is one line: the type, the key, and an optional comment.',
                            'type' => 'This key type is not recognised. Use ssh-ed25519, ssh-rsa or ecdsa.',
                            'body' => 'The key text looks damaged. Copy it again.',
                            'private' => 'That is a private key. Never paste it. Paste the .pub file instead.',
                        ],
                        'keyDetected' => '{type} key, {comment}',
                        'addedOn' => 'Added',
                        'lastUsed' => 'Last used',
                        'never' => 'Never',
                        'installOnAll' => 'Install on all servers',
                        'removeFromAll' => 'Remove from all servers',
                        'deleteKey' => 'Delete key',
                        'deleteKeyTitle' => 'Delete {name}?',
                        'deleteKeyBody' => 'The key is removed from every server it is installed on. Anyone using it can no longer sign in.',
                        'installedOn' => '{key} on {server}',
                        'noKeys' => 'No SSH keys yet',
                        'noKeysBody' => 'Add a public key, then choose the servers it can sign in to.',
                        'jobsTitle' => 'Job queue',
                        'jobsDescription' => 'Background work, by status. Retry what failed, or forget it.',
                        'jobsTable' => 'Jobs',
                        'job' => 'Job',
                        'queue' => 'Queue',
                        'attempts' => 'Attempts',
                        'when' => 'When',
                        'status' => 'Status',
                        'jobStatuses' => [
                            'waiting' => 'Waiting',
                            'active' => 'Running',
                            'delayed' => 'Delayed',
                            'completed' => 'Done',
                            'failed' => 'Failed',
                        ],
                        'retry' => 'Retry',
                        'forget' => 'Forget',
                        'retryFailed' => 'Retry all failed',
                        'forgetFailed' => 'Forget all failed',
                        'forgetTitle' => 'Forget {n} jobs?',
                        'forgetBody' => 'They are removed from the queue and the history. This cannot be undone.',
                        'retryTitle' => 'Retry {n} jobs?',
                        'retryBody' => 'They go back to the queue and run again.',
                        'details' => 'Details',
                        'errorLabel' => 'Error',
                        'payloadLabel' => 'Payload',
                        'noError' => 'No error recorded.',
                        'close' => 'Close',
                        'jobsEmpty' => 'No jobs',
                        'of' => '{a}/{b}',
                        'queueFilter' => 'Queue',
                        'statusGroup' => 'Job status',
                    ];

            return array_merge($base, ['ar' => $ar], $ar ? [
                'totalOne' => 'تحديث واحد', 'totalTwo' => 'تحديثان', 'totalFew' => '{n} تحديثات', 'totalMany' => '{n} تحديثًا',
                'forgetOne' => 'نسيان هذه المهمة؟', 'retryOne' => 'إعادة محاولة هذه المهمة؟', 'keyNoComment' => 'مفتاح {type}',
                'notAvailable' => 'لا يتوفر «{action}» والحالة: {state}.', 'justNow' => 'الآن',
            ] : [
                'totalOne' => '1 update', 'totalTwo' => '{n} updates', 'totalFew' => '{n} updates', 'totalMany' => '{n} updates',
                'forgetOne' => 'Forget this job?', 'retryOne' => 'Retry this job?', 'keyNoComment' => '{type} key',
                'notAvailable' => '{action} is not available while the status is {state}.', 'justNow' => 'just now',
            ], $labels);
        }
    }
@endphp
